version: '3'

services:
  dpass:
    image: dpass:20250528
    container_name: dpass-server
    pull_policy: never
    restart: always
    env_file:
      - .env
      - .env.production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT}:${APP_PORT}'  
    networks:
      - dpass_net

networks:
  dpass_net:
    name: dpass_net