version: '3'

services:
  dpass-server:
    # build: 从当前路径构建镜像
    build:
      context: .
      args:
        - PROJECT_DIR=${PROJECT_DIR}
    image: dpass:latest
    container_name: dpass-server
    restart: never
    env_file:
      - .env
      - .env.production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./logs/:${PROJECT_DIR}/logs/ # ./logs 日志文件挂载到容器外部
    # 当前服务启动之前先要把depends_on指定的服务启动起来才行
    networks:
      - dpass_net

networks:
  dpass_net:
    name: dpass_net
